using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace FleetariTowingService
{
    public class ItemTowingClass
    {
        public static List<string> Itemlist = new List<string>(new[]
        {
            "floor jack(itemx)",
            "lift",
            "motor hoist(itemx)",
            "house_door1",
            "sauna_door1",
            "Bed",
            "FLATBED",
            "SATSUMA(557kg)",
            "FERNDALE(1630kg)",
            "HAYOSIKO(1500kg)",
            "GIFU(750/450psi)",
            "KEKMET(350-400psi)",
            "JONNEZ ES(Clone)",
            "GFX",
            "ShitTank",
            "Cabin",
            "doorr",
            "doorl",
            "doorear",
            "JunkCar1",
            "JunkCar2",
            "JunkCar3",
            "BUS",
            "STATUSD",
            "mesh",
            "FacePissTrigger",
            "TeimoCollider",
            "table_pub",
            "BusStop 1",
            "BusStop 2",
            "Platform",
            "RagDoll",
            "thigh(right)",
            "thigh(leftx)",
            "leg(leftx)",
            "leg(right)",
            "shoulder(right)",
            "shoulder_left",
            "shoulder_right",
            "arm(right)",
            "arm_right",
            "arm_left",
            "shoulder(leftx)",
            "arm(leftx)",
            "shoulders(xxxxx)",
            "head",
            "spine_upper",
            "FITTAN",
            "POLICE1",
            "POLICE2",
            "VICTRO 1",
            "VAN_r",
            "POLSA 1",
            "VICTRO 4",
            "VICTRO 3_r",
            "VICTRO 2_r",
            "TRUCK 1",    
            "AMIS_r",    
            "FITTAN 2",    
            "TRAIN",
            "haybale",
            "haybale 1",     
            "haybale 2",     
            "haybale 3",     
            "haybale 4",     
            "haybale 5",     
            "haybale 6",     
            "haybale 7",     
            "haybale 8",     
            "haybale 9",     
            "haybale 10",     
            "haybale 11",     
            "haybale 12",     
            "haybale 13",     
            "haybale 14",     
            "haybale 15",     
            "lato_door1",    
            "lato_door2",    
            "haybale_plastic",    
            "haybale_plastic 1",    
            "haybale_plastic 2",    
            "haybale_plastic 3",    
            "haybale_plastic 4",    
            "haybale_plastic 5",    
            "haybale_plastic 6",    
            "haybale_plastic 7",    
            "haybale_plastic 8",    
            "haybale_plastic 9",    
            "haybale_plastic 10",    
            "haybale_plastic 11",    
            "haybale_plastic 12",    
            "haybale_plastic 13",    
            "haybale_plastic 14",    
            "haybale_plastic 15",    
            "well_cover(xxxxx)",    
            "BreakableWindow",    

        });
        public static List<string> VehicleList = new List<string>(new[]
        {
            "FLATBED",
            "SATSUMA(557kg)",
            "FERNDALE(1630kg)",
            "HAYOSIKO(1500kg)",
            "GIFU(750/450psi)",
            "KEKMET(350-400psi)",
            "JONNEZ ES(Clone)",
            "JunkCar1",
            "JunkCar2",
            "JunkCar3"

        });

    }
}

